style = defaultWithAlign

runner.dialect = scala213source3
docstrings.style = asterisk
maxColumn = 180
rewrite.rules = [RedundantBraces, RedundantParens, SortImports]
rewrite.scala3.convertToNewSyntax = true
spaces.inImportCurlyBraces = true
indentOperator.preset = spray

version = 3.11.5

# Use Scala 3 dialect for scala-3 directories
fileOverride {
  "glob:**/scala-3/**/*.scala" {
    runner.dialect = scala3
    rewrite.scala3.convertToNewSyntax = false
  }
}
