style = defaultWithAlign

runner.dialect = scala213source3
docstrings.style = asterisk
maxColumn = 180
rewrite.rules = [RedundantBraces, RedundantParens, SortImports]
rewrite.scala3.convertToNewSyntax = true
spaces.inImportCurlyBraces = true
indentOperator.preset = spray

version = 3.10.4
